version: 2.1

executors:
  default-executor:
    docker:
      - image: "cimg/node:8.17.0"
    resource_class: large

commands:
  setup:
    steps:
      - run:
          name: Setup
          command: |
            npm install
            npm update
            npm prune
  test:
    steps:
      - run:
          name: Test
          command: |
            npm run test
  deploy:
    steps:
      - run:
          name: Deploy
          command: |
            echo "export NPM_TAG=latest" >> $BASH_ENV
            echo "export NODE_ENV=production" >> $BASH_ENV
            echo "export RELEASE_TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $BASH_ENV
            npm run build
            VPKG=$($(npm bin)/json -f package.json version)
            echo "export VERSION=${VPKG}-prerelease.$(date +%Y%m%d%H%M%S)" >> $BASH_ENV
            npm --no-git-tag-version version $VERSION
  after_deploy:
    steps:
      - run:
          name: After Deploy
          command: |
            echo $VERSION

jobs:
  build-and-test:
    executor: default-executor
    steps:
      - checkout
      - setup
      - test
  deploy:
    executor: default-executor
    steps:
      - checkout
      - setup
      - deploy
      - after_deploy

workflows:
  build-and-test-workflow:
    when:
      not:
        and:
          - equal: [tsm/circleci, <<pipeline.git.branch>>]
    jobs:
      - build-and-test

  deploy-workflow:
    when:
      or:
        - equal: [master, <<pipeline.git.branch>>]
        - equal: [develop, <<pipeline.git.branch>>]
        - equal: [hotfix/*, <<pipeline.git.branch>>]
        - equal: [tsm/circleci, <<pipeline.git.branch>>]
    jobs:
      - build-and-test
      - deploy:
          context:
            - scratch-npm-creds
          requires:
            - build-and-test
